<script>
    import {
        Timeline,
        TimelineItem,
        TimelineSeparator,
        TimelineDot,
        TimelineConnector,
        TimelineContent,
        TimelineOppositeContent
    } from 'svelte-vertical-timeline';

    export let timeLineItems;
    let innerWidth = 0;
</script>

<svelte:window bind:innerWidth  />


{#if innerWidth === 0}
    <div>place holder</div>
{:else}
    <Timeline position="{innerWidth < 640 ? 'right' : 'alternate'}">
        {#each timeLineItems as item}
            <TimelineItem>
                <TimelineOppositeContent slot="opposite-content">
                    {item.date}
                </TimelineOppositeContent>
                <TimelineSeparator>
                    <TimelineDot />
                    <TimelineConnector />
                </TimelineSeparator>
                <TimelineContent>
                    <div>
                        <h3>{item.title}</h3>
                        <div class="flex">
                            <div class="m-2">
                                {#if item.image}
                                <img class="w-10 h-10" src="{item.image}"/>
                                {/if}
                            </div>
                            <div class="mx-1  max-w-[80%]">
                                <div class="text-sm">{item.description}</div>
                                {#if item.bullets && item.bullets.length > 0 }
                                    <ul class="list list-disc text-left ml-4 mt-1 text-sm">
                                        {#each item.bullets as bullet}
                                            <li>{bullet}</li>
                                        {/each }
                                    </ul>
                                {/if }
                            </div>
                        </div>
                    </div>
                </TimelineContent>
            </TimelineItem>
        {/each}
    </Timeline>
{/if}

<style>

    /* workaround with global because rollup removes the css as it,
     * does not detect the alternate generated by the timeline component */
    :global(.alternate:nth-of-type(even) .flex) {
        flex-direction: row-reverse;
        /*border: solid pink 1px;*/
    }

    :global(.timeline-opposite-content.right) {
        flex: 0 !important;
    }
</style>