name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  publish-container:

    runs-on: node:18-alpine

    steps:
    - name: Login to docker registry
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN

    - uses: actions/checkout@v3

    - name: Npm install

    - name: Build the Docker image
      run: docker build --file Dockerfile --tag meerman.xyz:latest .

    - name: Tag docker image
      run: docker tag meerman.xyz:latest ${{secrets.DOCKER_USER}}/meerman.xyz:latest

    - name: Publish the docker image
      run: docker push ${{secrets.DOCKER_USER}}/meerman.xyz:latest


